# Generated by Django 4.0 on 2021-12-09 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userloginhistory',
            old_name='last_updated',
            new_name='last_login',
        ),
    ]
